SET local check_function_bodies = off;

CREATE TABLE "public"."cash_config" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "amount"     numeric(12,2)            NOT NULL,
  "is_active"  boolean                  DEFAULT true,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "cash_config_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."cash_config"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cash_expenses" (
  "id"          uuid                     NOT NULL DEFAULT gen_random_uuid(),
  "title"       text                     NOT NULL,
  "description" text,
  "amount"      numeric(15,2)            NOT NULL,
  "spent_at"    date                     NOT NULL,
  "category"    text                     NOT NULL,
  "created_by"  uuid                     NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "cash_expenses_amount_check" CHECK ((amount > (0)::numeric)),
  CONSTRAINT "cash_expenses_category_check" CHECK ((category = ANY (ARRAY['ATK'::text, 'Konsumsi'::text, 'Acara'::text, 'Transportasi'::text, 'Lainnya'::text]))),
  CONSTRAINT "cash_expenses_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."cash_expenses"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cash_payments" (
  "id"          bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "period_id"   bigint                   NOT NULL,
  "member_id"   bigint                   NOT NULL,
  "amount"      numeric(12,2)            NOT NULL,
  "paid_at"     timestamp with time zone DEFAULT now(),
  "recorded_by" uuid                     NOT NULL,
  "note"        text,
  CONSTRAINT "cash_payments_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."cash_payments"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."cash_periods" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "config_id"  bigint,
  "start_date" date                     NOT NULL,
  "end_date"   date                     NOT NULL,
  "amount"     numeric(12,2)            NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "cash_periods_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."cash_periods"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."member" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "name"       text,
  CONSTRAINT "member_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."member"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"         uuid                     NOT NULL,
  "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text),
  "username"   text,
  "avatar_url" text,
  "email"      text,
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_username_key" UNIQUE (username),
  CONSTRAINT "username_length" CHECK ((char_length(username) >= 3))
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."cash_period" AS ENUM (
  'weekly',
  'monthly'
);

ALTER TABLE "public"."cash_config"
  ADD COLUMN "period" public.cash_period NOT NULL;

CREATE TYPE "public"."user_role" AS ENUM (
  'admin',
  'bendahara',
  'anggota'
);

ALTER TABLE "public"."profiles"
  ADD COLUMN "role" public.user_role DEFAULT 'anggota'::public.user_role;

CREATE OR REPLACE FUNCTION public.get_unpaid_periods (
  p_member_id bigint
)
  RETURNS TABLE (
    period_id   bigint,
    start_date  date,
    end_date    date,
    amount      numeric,
    paid_amount numeric
  )
  LANGUAGE sql
  AS $function$
  select
    cp.id as period_id,
    cp.start_date,
    cp.end_date,
    cp.amount,
    coalesce(sum(cpp.amount), 0) as paid_amount
  from public.cash_periods cp

  left join public.cash_payments cpp
    on cpp.period_id = cp.id
    and cpp.member_id = p_member_id

  group by
    cp.id,
    cp.start_date,
    cp.end_date,
    cp.amount

  having coalesce(sum(cpp.amount), 0) < cp.amount

  order by cp.start_date;
$function$;

CREATE OR REPLACE FUNCTION public.handle_cash_expenses_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
begin
    new.updated_at = now();
    return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
begin
  insert into public.profiles (
    id,
    username,
    avatar_url,
    role,
    email
  )
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    new.raw_user_meta_data->>'avatar_url',
    coalesce(
      (new.raw_user_meta_data->>'role')::public.user_role,
      'anggota'::public.user_role
    ),
    new.raw_user_meta_data->>'email'
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.has_role (
  required_role public.user_role
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = required_role
  );
$function$;

ALTER TABLE "public"."cash_periods"
  ADD CONSTRAINT "cash_periods_config_id_fkey" FOREIGN KEY (config_id) REFERENCES public.cash_config(id);

ALTER TABLE "public"."cash_payments"
  ADD CONSTRAINT "cash_payments_period_id_fkey" FOREIGN KEY (period_id) REFERENCES public.cash_periods(id);

ALTER TABLE "public"."cash_payments"
  ADD CONSTRAINT "cash_payments_member_id_fkey" FOREIGN KEY (member_id) REFERENCES public.member(id);

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."cash_expenses"
  ADD CONSTRAINT "cash_expenses_created_by_fkey" FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE RESTRICT;

ALTER TABLE "public"."cash_payments"
  ADD CONSTRAINT "cash_payments_recorded_by_fkey" FOREIGN KEY (recorded_by) REFERENCES public.profiles(id);

CREATE INDEX cash_expenses_category_idx ON public.cash_expenses USING btree (category);

CREATE INDEX cash_expenses_created_by_idx ON public.cash_expenses USING btree (created_by);

CREATE INDEX cash_expenses_spent_at_idx ON public.cash_expenses USING btree (spent_at DESC);

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER set_cash_expenses_updated_at
  BEFORE UPDATE ON public.cash_expenses
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_cash_expenses_updated_at();

CREATE POLICY "cash_config_admin_delete" ON "public"."cash_config"
  FOR DELETE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_config_admin_insert" ON "public"."cash_config"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_config_admin_update" ON "public"."cash_config"
  FOR UPDATE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role))
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_config_select_authenticated" ON "public"."cash_config"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Admins and treasurers can create cash expenses" ON "public"."cash_expenses"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::public.user_role, 'bendahara'::public.user_role]))))) AND (created_by = auth.uid())));

CREATE POLICY "Admins and treasurers can delete cash expenses" ON "public"."cash_expenses"
  FOR DELETE
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::public.user_role, 'bendahara'::public.user_role]))))));

CREATE POLICY "Admins and treasurers can update cash expenses" ON "public"."cash_expenses"
  FOR UPDATE
  TO "authenticated"
  USING (true)
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = ANY (ARRAY['admin'::public.user_role, 'bendahara'::public.user_role]))))));

CREATE POLICY "Authenticated users can view cash expenses" ON "public"."cash_expenses"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Enable read access for all users" ON "public"."cash_payments"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "cash_payments_admin_delete" ON "public"."cash_payments"
  FOR DELETE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_payments_admin_insert" ON "public"."cash_payments"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((public.has_role('admin'::public.user_role) AND (recorded_by = auth.uid())));

CREATE POLICY "cash_payments_admin_select" ON "public"."cash_payments"
  FOR SELECT
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_payments_admin_update" ON "public"."cash_payments"
  FOR UPDATE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role))
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_payments_bendahara_insert" ON "public"."cash_payments"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((public.has_role('bendahara'::public.user_role) AND (recorded_by = auth.uid())));

CREATE POLICY "cash_payments_bendahara_select" ON "public"."cash_payments"
  FOR SELECT
  TO "authenticated"
  USING (public.has_role('bendahara'::public.user_role));

CREATE POLICY "cash_payments_member_select" ON "public"."cash_payments"
  FOR SELECT
  TO "authenticated"
  USING ((EXISTS ( SELECT 1
   FROM public.member
  WHERE (member.id = cash_payments.member_id))));

CREATE POLICY "cash_periods_admin_delete" ON "public"."cash_periods"
  FOR DELETE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_periods_admin_insert" ON "public"."cash_periods"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_periods_admin_update" ON "public"."cash_periods"
  FOR UPDATE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role))
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "cash_periods_select" ON "public"."cash_periods"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."member"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON "public"."member"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Public profiles are viewable by everyone." ON "public"."profiles"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Users can insert their own profile." ON "public"."profiles"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can update own profile." ON "public"."profiles"
  FOR UPDATE
  TO PUBLIC
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "profiles_admin_update" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING (public.has_role('admin'::public.user_role))
  WITH CHECK (public.has_role('admin'::public.user_role));

CREATE POLICY "Anyone can upload an avatar." ON "storage"."objects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((bucket_id = 'avatars'::text));

CREATE POLICY "Avatar images are publicly accessible." ON "storage"."objects"
  FOR SELECT
  TO PUBLIC
  USING (((bucket_id = 'avatars'::text) AND storage.allow_any_operation(ARRAY['object.get_authenticated_info'::text, 'object.get_authenticated'::text])));

GRANT EXECUTE ON FUNCTION "public"."get_unpaid_periods"(bigint) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_cash_expenses_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."has_role"(public.user_role) TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cash_config" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cash_expenses" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cash_payments" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."cash_periods" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."member" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."cash_period" TO "postgres";

GRANT USAGE ON TYPE "public"."user_role" TO "postgres";

